"""Added Product table

Revision ID: 21984e5e52b7
Revises: 
Create Date: 2022-09-05 00:31:22.054983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21984e5e52b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('user',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    op.drop_table('sqlite_sequence')
    op.drop_table('User')
    op.drop_table('Product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('p_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(length=30), nullable=True),
    sa.Column('price', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('User',
    sa.Column('s_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.NUMERIC(precision=32), nullable=True),
    sa.Column('last_name', sa.NUMERIC(precision=32), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('password', sa.NUMERIC(precision=32), nullable=True),
    sa.Column('permissions', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('s_id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
